#!/usr/bin/env python3
"""Regenerate wheel-only Linux x86_64 dependency locks from version constraints."""

import email
import hashlib
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLATFORMS = [f"manylinux_2_{minor}_x86_64" for minor in range(35, 16, -1)] + ["manylinux2014_x86_64"]


def generate(kind: str, python: str) -> None:
    lines = (ROOT / "requirements/ci.txt").read_text().splitlines()
    if kind == "release":
        lines += (ROOT / "requirements/release.txt").read_text().splitlines()
    if kind == "minimum-qt":
        lines = [line for line in lines if not line.startswith(("PyQt6==", "PyQt6-Qt6=="))]
        lines += ["PyQt6==6.6.0", "PyQt6-Qt6==6.6.0"]
    with tempfile.TemporaryDirectory(prefix="qwarp-lock-") as temporary:
        folder = Path(temporary)
        requirements = folder / "input.txt"
        requirements.write_text("\n".join(sorted(set(lines))) + "\n")
        command = [
            sys.executable,
            "-m",
            "pip",
            "download",
            "--only-binary=:all:",
            "--python-version",
            python,
            "--implementation",
            "cp",
            "--dest",
            str(folder),
            "-r",
            str(requirements),
        ]
        for platform in PLATFORMS:
            command += ["--platform", platform]
        subprocess.run(command, check=True)
        locked = []
        for wheel in folder.glob("*.whl"):
            with zipfile.ZipFile(wheel) as archive:
                metadata_path = next(name for name in archive.namelist() if name.endswith(".dist-info/METADATA"))
                metadata = email.message_from_bytes(archive.read(metadata_path))
            digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
            locked.append(f"{metadata['Name']}=={metadata['Version']} --hash=sha256:{digest}")
        output = ROOT / "requirements/locks" / f"{kind}-py{python}.txt"
        output.parent.mkdir(exist_ok=True)
        output.write_text(
            "# Generated by scripts/lock_requirements.py; Linux x86_64, glibc >= 2.35.\n"
            + "\n".join(sorted(locked, key=str.lower))
            + "\n"
        )


if __name__ == "__main__":
    for version in ("3.11", "3.14"):
        for group in ("ci", "release"):
            generate(group, version)
    generate("minimum-qt", "3.11")
